<script setup>
import { onMounted, ref } from 'vue';
import { Check, X } from '@lucide/vue';
import { paymentService } from '../../services/paymentService';

const orders = ref([]); const loading = ref(true); const error = ref(''); const busyId = ref(null);
async function load() { loading.value = true; error.value = ''; try { orders.value = (await paymentService.adminPending({ page: 1, size: 50 })).items || []; } catch (caught) { error.value = caught.message || 'Could not load payment orders.'; } finally { loading.value = false; } }
async function act(order, action) { busyId.value = order.id; try { await (action === 'confirm' ? paymentService.adminConfirm(order.id) : paymentService.adminReject(order.id)); orders.value = orders.value.filter((item) => item.id !== order.id); } catch (caught) { error.value = caught.message || 'Could not update the payment order.'; } finally { busyId.value = null; } }
onMounted(load);
</script>
<template>
  <main class="mx-auto max-w-6xl px-5 py-8 sm:px-8"><p class="melodyhub-kicker">Premium</p><h1 class="melodyhub-section-title">Pending payments</h1><p class="mt-2 text-sm text-[#A1A1AA]">Verify the transfer note against your bank, then confirm or reject the order.</p><p v-if="error" class="mt-5 rounded-lg bg-red-500/10 px-4 py-3 text-sm text-red-200">{{ error }}</p><div v-if="loading" class="mt-6 text-sm text-[#A1A1AA]">Loading…</div><div v-else-if="orders.length === 0" class="mt-6 rounded-xl border border-white/10 bg-white/[0.02] px-6 py-14 text-center text-sm text-[#A1A1AA]">No pending payments.</div><div v-else class="mt-6 overflow-x-auto rounded-xl border border-white/10"><table class="w-full min-w-[720px] text-left text-sm"><thead class="border-b border-white/10 text-xs uppercase tracking-wide text-[#A1A1AA]"><tr><th class="p-4">Order</th><th class="p-4">Plan</th><th class="p-4">Amount</th><th class="p-4">Transfer note</th><th class="p-4">Created</th><th class="p-4 text-right">Actions</th></tr></thead><tbody><tr v-for="order in orders" :key="order.id" class="border-b border-white/5 last:border-0"><td class="p-4">#{{ order.id }}</td><td class="p-4">{{ order.planCode }}</td><td class="p-4">{{ new Intl.NumberFormat('vi-VN').format(order.amount) }} ₫</td><td class="p-4 font-mono text-[#20E878]">{{ order.transferNote }}</td><td class="p-4 text-[#A1A1AA]">{{ new Date(order.createdAt).toLocaleString() }}</td><td class="p-4"><div class="flex justify-end gap-2"><button class="grid size-8 place-items-center rounded bg-[#20E878] text-[#09090B] disabled:opacity-50" :disabled="busyId === order.id" title="Confirm" @click="act(order, 'confirm')"><Check :size="16" /></button><button class="grid size-8 place-items-center rounded border border-red-400/50 text-red-300 disabled:opacity-50" :disabled="busyId === order.id" title="Reject" @click="act(order, 'reject')"><X :size="16" /></button></div></td></tr></tbody></table></div></main>
</template>
